### ISSUE TITLE
Seed Data for REF.AdminX Tables

### ISSUE THREAD

**Issue by optimumcadence** [RMS-open-standards/RDOS#10]
Is there any seed data for the different geo tables: REF.AdminX and the City and PostalCode tables?

**Comment by paulsreed** [comment]
Hello Optimumcadence: 
Thank you for your question. Are you looking for examples of complete Addresses, including elements like postcode, admin1, postcode?
Or are you looking for lists of elements like admin1s, Postal Codes, etc. ?
Best,
Paul

**Comment by optimumcadence** [comment]
Hi Paul

I’m looking for the latter - seeding for e.g. US state, county lookups etc.

**Comment by paulsreed** [comment]
Hi Optimumcadence,

Would it be OK if we provided the seed data in CSV format?

**Comment by optimumcadence** [comment]
CSV would be great!

**Comment by kzaidain-rms** [comment]
The RDOS_Schema.xlsx now has two new worksheets for Admin1Code Examples and Admin2Code Examples. The admin1Code and admin2Code fields on the other worksheets link to these for easy accessibility.
