### ISSUE TITLE
Suggested improvements to packaging of edm2rdo download

### ISSUE THREAD

**Issue by andygrove** [RMS-open-standards/RDOS#8]
I downloaded the ubuntu version of edm2rdo and unzipped it. It created a nested directory structure of `Users/vpandey/Desktop/ubuntu` which isn't very helpful. I would expect it to create a directory named `edm2rdo-1.0.0` or similar. I would also suggest changing the name of the download file from `ubuntu-x64.zip` to `edm2rdo-ubuntu-x64.zip` and consider including the version number in the filename as well.

```
Archive:  ubuntu-x64.zip
   creating: Users/vpandey/Desktop/ubuntu-x64/
  inflating: Users/vpandey/Desktop/ubuntu-x64/Edm2Rdo  
  inflating: Users/vpandey/Desktop/ubuntu-x64/Edm2Rdo.pdb  
```

**Comment by cihanb** [comment]
thanks Andy. great suggestions. @vgadiyaram-rms FYI

**Comment by vgadiyaram-rms** [comment]
This has been Merged to master
